spring:
  application:
    name: eureka

server:
  port: 8761


eureka:
  instance:
    hostname: peer1
#    关闭client,启动一个eureka才能正常运行，否则需启动两个
#  client:
#    client:
#    serviceUrl:
#      defaultZone: http://peer2:8762/eureka
