#spring:
#  application:
#    name: eureka
#
#server:
#  port: 8761
#
#
#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: true #是否指定一个ip地址（false时会自动寻找本机ip，true提高启动速度），后期关闭
#    ip-address: 127.0.0.1
#  client:
#    register-with-eureka: false #是否把自己作为服务注册（自我注册）
#    fetch-registry: false #是否主动发现服务
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
